// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeqGTgf4MyiAez6zjsWgPVm75ktVkifhk',
    appId: '1:462991973077:web:cbb9e152f237a1aaaf605c',
    messagingSenderId: '462991973077',
    projectId: 'jemma-b0fcd',
    authDomain: 'jemma-b0fcd.firebaseapp.com',
    storageBucket: 'jemma-b0fcd.appspot.com',
    measurementId: 'G-JQEGMPG1HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9MBy4lvVsbnra4yiIiKuqkEzrFkvcmjo',
    appId: '1:462991973077:android:1d84d43ff33b067baf605c',
    messagingSenderId: '462991973077',
    projectId: 'jemma-b0fcd',
    storageBucket: 'jemma-b0fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgzbu6prfUFVg4Jd9xsbMZFvA4uV-90qw',
    appId: '1:462991973077:ios:481c0b6ffb616df1af605c',
    messagingSenderId: '462991973077',
    projectId: 'jemma-b0fcd',
    storageBucket: 'jemma-b0fcd.appspot.com',
    iosClientId: '462991973077-ggfso9vrdit70s45u4mue4rd8jo8lvd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCrossApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgzbu6prfUFVg4Jd9xsbMZFvA4uV-90qw',
    appId: '1:462991973077:ios:481c0b6ffb616df1af605c',
    messagingSenderId: '462991973077',
    projectId: 'jemma-b0fcd',
    storageBucket: 'jemma-b0fcd.appspot.com',
    iosClientId: '462991973077-ggfso9vrdit70s45u4mue4rd8jo8lvd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCrossApp',
  );
}
