// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwX6OuUmY2QxmWfZwmJSlp5zLI_nLAaPQ',
    appId: '1:774978952042:web:5f6d355259a86dfeaf2313',
    messagingSenderId: '774978952042',
    projectId: 'jemma-australia-d5fe3',
    authDomain: 'jemma-australia-d5fe3.firebaseapp.com',
    storageBucket: 'jemma-australia-d5fe3.appspot.com',
    measurementId: 'G-XH3CRBZERG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6DASY7tPex_Mcn2SXrsGkE4OfeS1FPEo',
    appId: '1:774978952042:android:ed5867df3815ba94af2313',
    messagingSenderId: '774978952042',
    projectId: 'jemma-australia-d5fe3',
    storageBucket: 'jemma-australia-d5fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZ3dU2GgxW-bB896oGzVKVmAfHv2xh24',
    appId: '1:774978952042:ios:19abaaf7aacf332faf2313',
    messagingSenderId: '774978952042',
    projectId: 'jemma-australia-d5fe3',
    storageBucket: 'jemma-australia-d5fe3.appspot.com',
    iosClientId: '774978952042-h4vrshr9vef11bu0709lmdbbij24ml8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCrossApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZ3dU2GgxW-bB896oGzVKVmAfHv2xh24',
    appId: '1:774978952042:ios:19abaaf7aacf332faf2313',
    messagingSenderId: '774978952042',
    projectId: 'jemma-australia-d5fe3',
    storageBucket: 'jemma-australia-d5fe3.appspot.com',
    iosClientId: '774978952042-h4vrshr9vef11bu0709lmdbbij24ml8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCrossApp',
  );
}
