import 'package:hive/hive.dart';
import 'package:new_cross_app/Login/enums/user_type.dart';

part 'user.g.dart';

/// An user of Jemma application.
@HiveType(typeId: 1)
class User extends HiveObject {
  @HiveField(0)
  int id;

  @HiveField(1)
  String token;

  /// Generated by the backend.

  @HiveField(2)
  UserType userType;

  User(this.id, this.token, this.userType);

  @override
  String toString() {
    return 'User{id: $id, token: $token, userType: $userType}';
  }

  User.fromJson(Map<String, dynamic> json)
      : id = json["id"],
        token = json["token"],
        userType = parseUserTypeString(json["user_type"]);
}
